### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by NeriusZar** [aretka/traders#1]
Persiskaityk šituos linkus:
Dependency Injection in general - https://www.freecodecamp.org/news/a-quick-intro-to-dependency-injection-what-it-is-and-when-to-use-it-7578c84fa88f/
Android Dependency Injection - https://developer.android.com/training/dependency-injection
Dependency injection tool'sas kurį naudosim. Šitą gali greit prabėt akim bet daug nesigilink
https://developer.android.com/training/dependency-injection/hilt-android

**Comment by aretka** [comment]
Dependency injection basics are learnt and some of them such as crypto api depenecy injection to constructor is already accomplished in the project.
